### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by sw00** [devMidgard/playcanvas-nodejs#1]
Checking out the project and running `node gameserver.js` gives an error. 

The repository is also missing a `package.json` file. For NodeJS projects you should check this in with all your dependencies and ignore `node_modules/` directory.

```
$ node gameserver.js
C:\Users\sett\Projects\playcanvas-nodejs\node_modules\bindings\bindings.js:83
        throw e
        ^

Error: The specified module could not be found.
\\?\C:\Users\sett\Projects\playcanvas-nodejs\node_modules\gl\build\Release\webgl.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:736:18)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (C:\Users\sett\Projects\playcanvas-nodejs\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\sett\Projects\playcanvas-nodejs\node_modules\gl\webgl.js:4:35)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
```

**Comment by devMidgard** [comment]
Hi, this has been fixed and the project no longer requires the 'gl' module, instead I've nullified all functions so all calls point to an empty function and the engine just runs.

You will however need to 'npm install':
- canvas-mock.
- websocket.
- jsdom.
- request.

Let me know if you can run the project and I will happily close the issue.

Also on your comment on the missing package.json, I will look into it, however this playcanvas node module isn't publicly available throught npm install, so the only way to get it is to download it from here.

**Comment by sw00** [comment]
Thank you for the swift response.  I'm moving forward without using this now but for your benefit here's what I get when checking out latest master and running the following commands:

```
git clean -fd
npm install
npm install canvas-mock websocket jsdom request
```

```
$ node gameserver.js
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'ammo'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\sett\Projects\playcanvas-nodejs\node_modules\playcanvas\index.js:97:15)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
```

**Comment by devMidgard** [comment]
Fixed on latest commit, please confirm if you can :)

**Comment by sw00** [comment]
I can confirm that `gameserver.js` now executes. Thanks!
